### ISSUE TITLE
Use PHP from path if no php-project.executablePath

### ISSUE THREAD

**Issue by harmsk** [keyblade95/vscode-php-project#1]
Instead of requiring users to set php-project.executablePath, php.validate.executablePath, or php.validate.executablePath, use the php from the system path only if the above config options are not set.

Would you be open to this change? Would you accept a pull request for such a change?

**Comment by federicoparroni** [comment]
Hi! Yes, of course!

**Comment by harmsk** [comment]
I submitted a pull request. Please let me know if you would like any changes.

@keyblade95, do you have any estimate when you might be able to merge this and release it? I'm asking because I'm planning the rollout of this extension for my classes.

**Comment by federicoparroni** [comment]
Thank you so much for your contribution. I have merged your changes just now.
I am going to republish the extension in a few hours.
